### ISSUE TITLE
Is rssi calculation correct?

### ISSUE THREAD

**Issue by cclauss** [schollz/howmanypeoplearearound#18]
https://github.com/schollz/howmanypeoplearearound/blob/master/howmanypeoplearearound/__main__.py#L159-L161  Is this correct?  It probably is correct, and my knowledge is weak.  :-(

**Comment by schollz** [comment]
Ha, its incorrect. Thanks :)

**Comment by schollz** [comment]
I fixed it now: https://github.com/schollz/howmanypeoplearearound/commit/41dca3631929d632f64ee45d4609312c64d2a91d
