### ISSUE TITLE
Will it detect only certain cellphones

### ISSUE THREAD

**Issue by AshayAgrawal** [schollz/howmanypeoplearearound#19]
Help needed- Does its detect only phones listed in the code? It detects wonderfully my HTC phone, but not OnePlus, MI or Xiomi phone.

Issue - The count of cellphones takes into account rssi~0 also, which seems to be incorrect output.

**Comment by schollz** [comment]
Yes [it detects only a subset of all cellphones](https://github.com/schollz/howmanypeoplearearound/blob/master/howmanypeoplearearound/__main__.py#L172-L183). These cellphones are popular in North America. 

If you don't mind, you can add those cell phones to the list in a PR request. You just need to find their OUI name which will be printed if you run `howmanypeoplarearound -v` (which prints ALL things that it sees) or run `howmanypeoplearearound --allmacaddresses --jsonprint` which will print as a nice JSON.

**Comment by AshayAgrawal** [comment]
I thought this. Thanks a lot for your help and marvelous project. 

It detects the phone OnePlus now. Below is the output when I ran howmanypeoplarearound -v.

(u'00:00:be:47:f1:10', 'THE NTI GROUP', False)
(u'ec:9b:f3:ce:7f:1f', 'SAMSUNG ELECTRO-MECHANICS(THAILAND)', False)
(u'a8:66:7f:1f:1e:38', 'Apple, Inc.', True)
(u'1c:5f:2b:3d:65:70', 'D-Link International', False)
(u'0c:d2:b5:5f:23:14', 'Binatone Telecommunication Pvt. Ltd', False)
(u'1c:5f:2b:3d:8a:aa', 'D-Link International', False)
(u'd4:0b:1a:f4:86:c2', 'HTC Corporation', True)
(u'1c:5f:2b:3d:65:60', 'D-Link International', False)
(u'6c:72:20:f2:1a:91', 'D-Link International', False)
(u'60:92:17:59:6b:24', 'Apple, Inc.', True)
(u'1c:5f:2b:3d:65:10', 'D-Link International', False)
(u'c8:f2:30:d5:86:bc', 'GUANGDONG OPPO MOBILE TELECOMMUNICATIONS CORP.,LTD', True)
(u'50:2b:73:06:ba:40', 'Tenda Technology Co.,Ltd.Dongguan branch', False)
(u'c0:ff:d4:bb:9e:c7', 'NETGEAR', False)
(u'1c:5f:2b:3d:85:2d', 'D-Link International', False)
(u'e8:cc:18:ad:3d:78', 'D-Link International', False)
(u'90:8d:78:05:6a:9c', 'D-Link International', False)
(u'e0:2c:b2:f3:3b:3c', 'Lenovo Mobile Communication (Wuhan) Company Limited', False)
(u'e8:cc:18:ad:3d:81', 'D-Link International', False)
(u'b0:e2:35:54:de:3f', 'Xiaomi Communications Co Ltd', False)
(u'94:65:9c:65:31:00', 'Intel Corporate', False)
(u'c0:ee:fb:52:5a:6f', 'OnePlus Tech (Shenzhen) Ltd', False)
(u'00:00:c5:db:0f:20', 'ARRIS Group, Inc.', False)
(u'00:1c:c0:58:e5:f4', 'Intel Corporate', False)
(u'18:89:5b:66:65:b8', 'Samsung Electronics Co.,Ltd', True)
(u'1c:5f:2b:3d:65:50', 'D-Link International', False)
(u'fc:b0:c4:64:d0:c4', 'Shanghai DareGlobal Technologies Co.,Ltd', False)
(u'fc:b0:c4:64:d0:c5', 'Shanghai DareGlobal Technologies Co.,Ltd', False)
(u'90:8d:78:05:a3:ac', 'D-Link International', False)
(u'c8:d7:79:c2:2c:da', 'Qingdao Haier Telecom Co.\\uff0cLtd', False)
(u'0c:d2:b5:5f:31:bf', 'Binatone Telecommunication Pvt. Ltd', False)
(u'c0:ee:fb:52:5a:47', 'OnePlus Tech (Shenzhen) Ltd', False)

howmanypeoplearearound --allmacaddresses --jsonprint is giving me error saying, Error: no such option: --allmacaddresses. Kindly let me know, so that I can create a nice JSON and share.

**Comment by schollz** [comment]
> Error: no such option: --allmacaddresses

Try upgrading with `pip install --upgrade howmanypeoplearearound`

**Comment by schollz** [comment]
I added those two OUIs for cellphones now: https://github.com/schollz/howmanypeoplearearound/commit/41dca3631929d632f64ee45d4609312c64d2a91d

**Comment by AshayAgrawal** [comment]
Thanks Zack. 

Also, I got the json,xlsx with more OUIs. 
[result.txt](https://github.com/schollz/howmanypeoplearearound/files/1016250/result.txt)
[result.xlsx](https://github.com/schollz/howmanypeoplearearound/files/1016252/result.xlsx)
Do you want me to open a new request for it? 

I am also detecting D-Link, which is mostly is a wi-fi router. How will we make sure, we don't mistake a cell phone with a router?
