### ISSUE TITLE
Most Basic Hardware Implementation

### ISSUE THREAD

**Issue by adamsiem** [schollz/howmanypeoplearearound#28]
What is the simplest standalone hardware setup you would recommend for this?

What service would you run to be able to access the graphed results on another device's web browser?

**Comment by schollz** [comment]
> simplest standalone hardware

A Raspberry Pi 3 with one of these : http://www.tp-link.com/us/download/TL-WN722N.html. Works to about $50.

> What service would you run to be able to access the graphed results

This is my favorite web hosting server: https://caddyserver.com/. Download and just run `caddy` in the folder with the graphed results and you can access via http://YOUR_IP:2015.

**Comment by adamsiem** [comment]
Great. Thank you!

Do you know if the ASUS USB-AC51 AC600 is compatible? (It is the most compact.)

Also, what about the Raspberry Pi Zero W? Would that form factor work? With or without a USB network adapter?

**Comment by schollz** [comment]
Not sure if that ASUS is compatible.
Pi Zero W would work, I think just fine. It needs to also have a WiFi onboard (similar to the Pi 3) so that you can connect to it. The WiFi card that is used for `howmanypeoplearearound` won't allow connections during the scan.
