### ISSUE TITLE
Video Tutorials

### ISSUE THREAD

**Issue by harshil2105** [schollz/howmanypeoplearearound#38]
It's basically self explanatory but still there are very less video explainations,kindly add some video Tutorials as there are many noobs and this project is very cool

**Comment by harshil2105** [comment]
I can only find this video with some proper explanation https://youtu.be/dLzouUfJyMM

**Comment by schollz** [comment]
Thanks, this is a good request!

**Comment by harshil2105** [comment]
Boss you can add that video into your readme https://youtu.be/dLzouUfJyMM
