### ISSUE TITLE
Would this work on a macbook pro?

### ISSUE THREAD

**Issue by hadsed** [schollz/howmanypeoplearearound#5]

**Comment by kevchentw** [comment]
yes, I have tested successfully on my MacBook Pro with build-in wifi.

**Comment by vanarpsharma** [comment]
I keep getting this in macbook pro: -
```Found no signals, are you sure en1 supports monitor mode?```
any workaround?

**Comment by schollz** [comment]
It might be a `tshark` permissions issue. Did you allow non-root? You can try running in sudo to see if it works. But, as per the README, you can update `tshark` it so it can be run as non-root:

```
sudo dpkg-reconfigure wireshark-common     (select YES)
sudo usermod -a -G wireshark $USER
```

You will need to logout and log back in for changes to effect.

**Comment by brettinternet** [comment]
1. `brew install wireshark`
2. make sure you can run `tshark` without `sudo`. 
http://stackoverflow.com/questions/41126943/wireshark-you-dont-have-permission-to-capture-on-that-device-mac

**Comment by viosey** [comment]
1. brew install wireshark
2. pip install howmanypeoplearearound
3. use `en0` as Specify WiFi adapter (use ifconfig to determine)

**Comment by cclauss** [comment]
Can this issue be closed?

**Comment by ansell** [comment]
Yes, it works for me on MacbookPro using en0

**Comment by cclauss** [comment]
@hadsed Can this issue be closed?

**Comment by cclauss** [comment]
@schollz Can you please close this issue?
